[package]
name = "rusty_chessboard"
version = "0.1.0"
authors = ["Tomn0 <m2foster@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]